TERRAINS: dict[str, str] = {
    "FARM": "#98FB98",
    "MOUNTAIN": "#829696",
    "FOREST": "#00b200",
    "LAKE": "#0077ff",
    "DESERT": "#ffd232",
    "FOG": "#e0e0e0",
    "CITY": "#000000",
    "SWAMP": "#2e8b57",
    "SNOW": "#ffffff",
    "JUNGLE": "#228b22",
    "VOLCANO": "#ff4500",
    "BEACH": "#f5deb3",
    "OCEAN": "#000080",
    "GRASSLAND": "#7cfc00",
    "HILLS": "#808080",
    "TUNDRA": "#708090",
    "WASTELAND": "#8b4513",
    "MARSH": "#556b2f",
    "PLAINS": "#ff7f50",
}

ICONS: dict[str, str] = {
    "Akaford": "akaford.png",
    "Animal Skull": "animal-skull.png",
    "Bridge": "bridge.png",
    "Camp": "camp.png",
    "Cave": "cave.png",
    "Holy Oak": "holy-oak.png",
    "Mine": "mine.png",
    "Pillar": "pillar.png",
    "Pyramid": "pyramid.png",
    "Ruin": "ruin.png",
    "Swords Emblem": "swords-emblem.png",
    "Temple": "temple.png",
    "Tower": "tower.png",
    "Village": "village.png",
    "Wall": "wall.png",
}
